sudo: required #is required to use docker service in travis

language: python
python:
  - "3.6"

services:
  - docker # required, but travis uses older version of docker :(

install:
  - echo "install nothing!" # put your normal pre-testing installs here

script:
  - echo "no tests!" # put your normal testing scripts here

after_success:
  - echo "execute nothing. # These are the scripts for post execution
  
# sadly, travis doesn't cache docker builds yet, so each build will take a while :-(
